// GENERATED by scripts/bootstrap-accounts.ts. Public addresses only — safe to commit.
// Re-run `pnpm bootstrap:accounts` to refresh. Never put private keys here.
import type { Address } from 'viem';

export interface MandateAddresses {
  /** Demo accounts on Base Sepolia: SA address for smart-account roles, EOA otherwise. Keyed by role id. */
  accounts: Partial<Record<string, Address>>;
  /** Base Sepolia governance contracts (filled by the deploy task). */
  baseSepolia: { token?: Address; governor?: Address };
  /** Base mainnet governance contracts (filled by the mainnet task). */
  baseMainnet: { token?: Address; governor?: Address };
}

export const ADDRESSES: MandateAddresses = {
  accounts: {},
  baseSepolia: {},
  baseMainnet: {},
};
