/**
 * Bootstrap the Mandate demo accounts. RUN THIS LOCALLY — it touches your keys.
 *
 *   pnpm bootstrap:accounts
 *
 * What it does:
 *   1. For each role, reads its private key from .env. If missing, generates a
 *      fresh throwaway key and appends it to .env (never printed, never committed).
 *   2. Derives each role's on-chain address (EOA, or a MetaMask Hybrid smart account).
 *   3. Reads Base Sepolia ETH + USDC balances and prints a funding checklist.
 *   4. Writes the PUBLIC addresses to packages/shared/src/addresses.ts (safe to commit).
 *
 * It never prints private keys and never sends a transaction. Funding the printed
 * addresses (via a faucet) is your step — keys stay on your machine.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { config as loadDotenv } from 'dotenv';
import {
  createPublicClient,
  erc20Abi,
  formatEther,
  formatUnits,
  http,
  type Address,
  type Hex,
  type PublicClient,
} from 'viem';
import { generatePrivateKey } from 'viem/accounts';
import { baseSepolia } from 'viem/chains';

import {
  ACCOUNT_ROLES,
  deriveSmartAccountAddress,
  eoaAddress,
  fundingPlan,
  type AccountBalance,
} from '../src/accounts.js';
import { ADDRESSES, type MandateAddresses } from '../src/addresses.js';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const SHARED_SRC = path.resolve(SCRIPT_DIR, '../src');
const REPO_ROOT = path.resolve(SCRIPT_DIR, '../../..');
const ENV_PATH = path.join(REPO_ROOT, '.env');
const ADDRESSES_PATH = path.join(SHARED_SRC, 'addresses.ts');

/** Official Circle USDC on Base Sepolia. */
const BASE_SEPOLIA_USDC: Address = '0x036CbD53842c5426634e7929541eC2318f3dCF7e';
const DEFAULT_RPC = 'https://sepolia.base.org';

function isPrivateKey(value: string | undefined): value is Hex {
  return typeof value === 'string' && /^0x[0-9a-fA-F]{64}$/.test(value.trim());
}

/** Ensure every role has a key in .env, generating throwaway keys for any that are missing. */
function ensureKeys(): { keys: Record<string, Hex>; generated: string[] } {
  loadDotenv({ path: ENV_PATH });
  const keys: Record<string, Hex> = {};
  const generated: string[] = [];
  const appended: string[] = [];

  for (const role of ACCOUNT_ROLES) {
    const existing = process.env[role.envKey];
    if (isPrivateKey(existing)) {
      keys[role.id] = existing.trim() as Hex;
      continue;
    }
    const fresh = generatePrivateKey();
    keys[role.id] = fresh;
    generated.push(role.id);
    appended.push(`${role.envKey}=${fresh}`);
  }

  if (appended.length > 0) {
    const header = fs.existsSync(ENV_PATH) ? '' : 'MANDATE_ENV=development\n';
    const block = `\n# Throwaway demo keys generated by bootstrap:accounts — do not reuse on mainnet.\n${appended.join('\n')}\n`;
    fs.appendFileSync(ENV_PATH, header + block);
  }
  return { keys, generated };
}

async function deriveAddress(
  client: PublicClient,
  roleKind: 'smartAccount' | 'eoa',
  privateKey: Hex,
): Promise<Address> {
  return roleKind === 'smartAccount'
    ? deriveSmartAccountAddress(client, privateKey)
    : eoaAddress(privateKey);
}

async function readBalance(client: PublicClient, address: Address): Promise<AccountBalance> {
  const [wei, usdcRaw] = await Promise.all([
    client.getBalance({ address }),
    client
      .readContract({ address: BASE_SEPOLIA_USDC, abi: erc20Abi, functionName: 'balanceOf', args: [address] })
      .catch(() => 0n),
  ]);
  return { eth: Number(formatEther(wei)), usdc: Number(formatUnits(usdcRaw, 6)) };
}

function renderAddressesFile(data: MandateAddresses): string {
  return `// GENERATED by scripts/bootstrap-accounts.ts. Public addresses only — safe to commit.
// Re-run \`pnpm bootstrap:accounts\` to refresh. Never put private keys here.
import type { Address } from 'viem';

export interface MandateAddresses {
  /** Demo accounts on Base Sepolia: SA address for smart-account roles, EOA otherwise. Keyed by role id. */
  accounts: Partial<Record<string, Address>>;
  /** Base Sepolia governance contracts (filled by the deploy task). */
  baseSepolia: { token?: Address; governor?: Address; proposalId?: string };
  /** Base mainnet governance contracts (filled by the mainnet task). */
  baseMainnet: { token?: Address; governor?: Address; proposalId?: string };
}

export const ADDRESSES: MandateAddresses = ${JSON.stringify(data, null, 2)};
`;
}

async function main(): Promise<void> {
  console.log('› Bootstrapping Mandate demo accounts (Base Sepolia)\n');
  const { keys, generated } = ensureKeys();
  if (generated.length > 0) {
    console.log(`  generated ${generated.length} throwaway key(s) → appended to .env: ${generated.join(', ')}`);
    console.log('  (private keys were NOT printed; .env is gitignored)\n');
  }

  const rpc = process.env.BASE_SEPOLIA_RPC_URL || DEFAULT_RPC;
  const client = createPublicClient({ chain: baseSepolia, transport: http(rpc) }) as PublicClient;

  const addresses: Record<string, Address> = {};
  const balances: Record<string, AccountBalance> = {};
  for (const role of ACCOUNT_ROLES) {
    const address = await deriveAddress(client, role.kind, keys[role.id]);
    addresses[role.id] = address;
    balances[role.id] = await readBalance(client, address);
  }

  const plan = fundingPlan(addresses, balances);
  console.log('  Account matrix (rpc: ' + rpc + '):');
  for (const role of ACCOUNT_ROLES) {
    const need = plan.find((p) => p.id === role.id)!;
    const bal = balances[role.id];
    const status = need.funded ? '✓ funded' : '✗ FUND';
    console.log(`    ${status}  ${role.label.padEnd(22)} ${addresses[role.id]}`);
    console.log(
      `             ${role.kind.padEnd(13)} bal: ${bal.eth.toFixed(4)} ETH / ${bal.usdc.toFixed(2)} USDC` +
        (need.funded ? '' : `  → need +${need.needEth} ETH${need.needUsdc ? ` / +${need.needUsdc} USDC` : ''}`),
    );
  }

  // Persist public addresses; preserve any contract addresses already recorded.
  const next: MandateAddresses = {
    accounts: addresses,
    baseSepolia: ADDRESSES.baseSepolia,
    baseMainnet: ADDRESSES.baseMainnet,
  };
  fs.writeFileSync(ADDRESSES_PATH, renderAddressesFile(next));
  console.log(`\n  wrote ${path.relative(REPO_ROOT, ADDRESSES_PATH)}`);

  const unfunded = plan.filter((p) => !p.funded);
  if (unfunded.length > 0) {
    console.log('\n  Fund these before running the demo:');
    console.log('    • Base Sepolia ETH faucet:  https://www.alchemy.com/faucets/base-sepolia');
    console.log('    • Base Sepolia USDC faucet: https://faucet.circle.com  (select Base Sepolia)');
    for (const need of unfunded) {
      console.log(
        `    • ${need.address}  +${need.needEth} ETH${need.needUsdc ? ` and +${need.needUsdc} USDC` : ''}`,
      );
    }
  } else {
    console.log('\n  All accounts funded. ✓');
  }
}

main().catch((err) => {
  console.error('\nbootstrap:accounts failed:', err instanceof Error ? err.message : err);
  process.exitCode = 1;
});
